name: Semgrep PR Check

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  pr-security-check:
    name: PR Security Check
    uses: Basis-Theory/public-security-workflows/.github/workflows/pr-check.yml@master
    secrets: inherit